### ISSUE TITLE
Safely modify a constraint tree

### ISSUE THREAD

**Issue by stelmo** [COBREXA/ConstraintTrees.jl#32]
At the moment we have mutable constraint trees, which is very handy for manipulating complex structures, e.g. changing bounds etc. The problem is that this is a common pattern:
```julia
wt = simplified_enzyme_constrained_flux_balance_constraints(
        model;
        reaction_isozymes,
        gene_product_molar_masses,
        capacity = 400.0, # mg/gDW
        interface = :identifier_prefixes,
)
 wt.fluxes[rxn_id].bound = C.Between(-1000, 1000)
```
but it won't always work, because you also need to do:
```julia
wt.fluxes_forward[rxn_id].bound = C.Between(0, 1000)
wt.fluxes_reverse[rxn_id].bound = C.Between(0, 1000)
wt.interface.exchanges[rxn_id].bound = C.Between(-1000, 1000)
```
This makes is really easy to get incorrect results results if you don't know all the places the original flux bound is also implicitly present...

**Comment by exaexa** [comment]
OK so what we can do:

- disable the mutability of the main structures, so that people don't kill it randomly themselves
- instead provide something like `wt = C.patch(wt, (:fluxes_forward, rxn_id, :bound, :upper), 1000.0)` which people need to google so they certainly won't miss the documentation saying that this is a big nono
- have the good way documented (if the `model` is wrong, change it before you convert it to a CT)

does that sound ok?

**Comment by exaexa** [comment]
we'd need lenses to do this properly. :(

**Comment by stelmo** [comment]
This will definitely causes issues, especially in more complex models with more derived bounds. Basically 2 things:
1. I like being able to quickly modify the constraint types manually, e.g. `wt.fluxes[rxn_id].bound = C.Between(-1000, 1000)`
2. I want changes that affect other variables to either warn me or make it obvious that I am missing something

**Comment by exaexa** [comment]
yeah the issue is that 1 and 2 are not cleanly possible to combine because of how julia works. I was digging into that lately but everything is just kinda worse. Let's keep this open for ideas

**Comment by exaexa** [comment]
ok actually, can you test if either of these would do?

- https://github.com/JuliaObjects/Accessors.jl
- https://github.com/jw3126/Setfield.jl

if all OK we can just recommend these in documentation and avoid pulling in dependencies.

**Comment by exaexa** [comment]
ok the total price tag is:

- we need to depend on ConstructionBase.jl
- we add this overload:

```julia
ConstructionBase.setproperties(x::C.Tree{T}, props::NamedTuple) where T = C.Tree{T}(x..., pairs(props)...)
```

**Comment by stelmo** [comment]
Okay, but should we now make the trees immutable again?

**Comment by stelmo** [comment]
And this would solve issue 1 nicely, but issue 2 seems unsolvable without some sort of tracking structure, telling you what the dependency structure of all the constraints is?

**Comment by exaexa** [comment]
> Okay, but should we now make the trees immutable again?

Not really, I don't want to break it for people who "do" the safety themselves.

re issue 2 you mean "model variables" or "julia variables" ? (but yeah both are unsolvable :D :D )
